namespace Hercules.Cache;

/// <summary>
///     Cache class — classifies cached values by their data type.
///     Controls which TTL, sensitivity rules, and invalidation scope apply.
/// </summary>
public enum CacheClass
{
    /// <summary>Embedding vectors for skills and inputs (generated by IEmbeddingProvider).</summary>
    Embedding,

    /// <summary>Deterministic routing decisions (skill ID from DeterministicRouter).</summary>
    RoutingDecision,

    /// <summary>LLM provider capability detection results (vision, function calling, etc.).</summary>
    LlmCapability,

    /// <summary>Provider-supported prompt prefixes per LLM client (static per provider/model).</summary>
    LlmPromptPrefix,

    /// <summary>Deterministic tool execution results (same input → same output).</summary>
    DeterministicToolResult,
}
