using Hercules.Mesh;
using Hercules.Mesh.Audit;
using Hercules.Mesh.Policy;
using Hercules.Mesh.Transport;
using Microsoft.Extensions.Logging;
using Moq;
using Xunit;

namespace Hercules.Agent.Tests.Phase3Tests;

/// <summary>
///     Phase 3: task_041 — Inter-agent audit trail tests.
///     Tests: MeshAuditService, all audit sinks, MeshAuditConfig defaults.
/// </summary>
public class MeshAuditTests : IDisposable
{
    // ── Helpers ──────────────────────────────────────────────────────────────

    private static InterAgentAuditRecord MakeRecord(string eventType = "outbound_delegation")
        => new()
        {
            EventType = eventType,
            TraceId = "trace-001",
            RootRequestId = "root-001",
            RequestId = "req-001",
            SenderAgentId = "agent-a",
            ReceiverAgentId = "agent-b",
            Intent = "csharp-refactor",
            PayloadHash = "abc123",
            DataClassification = DataClassification.Internal,
            PolicyDecision = "Allowed",
            CostUsd = 0.01m,
            LatencyMs = 150.5,
            ResponseHash = "def456",
            Outcome = DelegationOutcome.Ok,
            DelegationDepth = 1,
            HopCount = 2,
            TransportKind = "Http"
        };

    private static MeshAuditConfig DefaultConfig()
        => new() { Enabled = true, SerilogSinkEnabled = true, OpenTelemetrySinkEnabled = false, FileSinkEnabled = false };

    // ── MeshAuditConfig defaults ─────────────────────────────────────────────

    [Fact]
    public void MeshAuditConfig_Defaults_AreSane()
    {
        var cfg = new MeshAuditConfig();

        Assert.True(cfg.Enabled);
        Assert.True(cfg.SerilogSinkEnabled);
        Assert.True(cfg.OpenTelemetrySinkEnabled);
        Assert.False(cfg.FileSinkEnabled);
        Assert.Equal("mesh-audit", cfg.FileSinkDirectory);
        Assert.True(cfg.PayloadHashEnabled);
        Assert.False(cfg.RedactPayloads);
        Assert.Equal(10_000, cfg.MaxPayloadLengthForHash);
        Assert.True(cfg.CostTrackingEnabled);
        Assert.Equal(1.0, cfg.SampleRate);
    }

    // ── InterAgentAuditRecord ───────────────────────────────────────────────

    [Fact]
    public void InterAgentAuditRecord_HasAutoGeneratedId()
    {
        var r1 = new InterAgentAuditRecord { EventType = "test" };
        var r2 = new InterAgentAuditRecord { EventType = "test" };

        Assert.NotEmpty(r1.Id);
        Assert.NotEmpty(r2.Id);
        Assert.NotEqual(r1.Id, r2.Id);
    }

    [Fact]
    public void InterAgentAuditRecord_TimestampIsUtcNow()
    {
        var before = DateTimeOffset.UtcNow.AddSeconds(-1);
        var r = new InterAgentAuditRecord { EventType = "test" };
        var after = DateTimeOffset.UtcNow.AddSeconds(1);

        Assert.InRange(r.Timestamp, before, after);
    }

    [Fact]
    public void InterAgentAuditRecord_DefaultsOutcomeToUnknown()
    {
        var r = new InterAgentAuditRecord { EventType = "test" };
        Assert.Equal(DelegationOutcome.Unknown, r.Outcome);
    }

    [Fact]
    public void InterAgentAuditRecord_DefaultsClassificationToPublic()
    {
        var r = new InterAgentAuditRecord { EventType = "test" };
        Assert.Equal(DataClassification.Public, r.DataClassification);
    }

    // ── SerilogMeshAuditSink ────────────────────────────────────────────────

    [Fact]
    public async Task SerilogMeshAuditSink_WriteAsync_LogsOkEvent_AtInformationLevel()
    {
        var loggerMock = new Mock<ILogger<MeshAuditService>>();
        var cfg = DefaultConfig();
        var sink = new SerilogMeshAuditSink(loggerMock.Object, cfg);
        var record = MakeRecord("outbound_delegation");

        await sink.WriteAsync(record);

        loggerMock.Verify(
            x => x.Log(
                LogLevel.Information,
                It.IsAny<EventId>(),
                It.Is<It.IsAnyType>((v, t) => true),
                null,
                It.IsAny<Func<It.IsAnyType, Exception?, string>>()),
            Times.AtLeastOnce);
    }

    [Fact]
    public async Task SerilogMeshAuditSink_WriteAsync_LogsPolicyDenied_AtWarningLevel()
    {
        var loggerMock = new Mock<ILogger<MeshAuditService>>();
        var cfg = DefaultConfig();
        var sink = new SerilogMeshAuditSink(loggerMock.Object, cfg);
        var record = new InterAgentAuditRecord
        {
            EventType = "outbound_delegation",
            TraceId = "trace-001",
            RootRequestId = "root-001",
            RequestId = "req-001",
            SenderAgentId = "agent-a",
            ReceiverAgentId = "agent-b",
            Intent = "csharp-refactor",
            PayloadHash = "abc123",
            DataClassification = DataClassification.Internal,
            PolicyDecision = "Denied",
            PolicyReason = "Intent not in allow-list",
            Outcome = DelegationOutcome.PolicyDenied,
            DelegationDepth = 1,
            HopCount = 2
        };

        await sink.WriteAsync(record);

        loggerMock.Verify(
            x => x.Log(LogLevel.Warning, It.IsAny<EventId>(),
                It.Is<It.IsAnyType>((v, t) => true), null,
                It.IsAny<Func<It.IsAnyType, Exception?, string>>()),
            Times.AtLeastOnce);
    }

    [Fact]
    public async Task SerilogMeshAuditSink_WriteAsync_LogsError_AtErrorLevel()
    {
        var loggerMock = new Mock<ILogger<MeshAuditService>>();
        var cfg = DefaultConfig();
        var sink = new SerilogMeshAuditSink(loggerMock.Object, cfg);
        var record = new InterAgentAuditRecord
        {
            EventType = "outbound_delegation",
            TraceId = "trace-001",
            RootRequestId = "root-001",
            RequestId = "req-001",
            SenderAgentId = "agent-a",
            ReceiverAgentId = "agent-b",
            Intent = "csharp-refactor",
            PayloadHash = "abc123",
            DataClassification = DataClassification.Internal,
            PolicyDecision = "Allowed",
            Outcome = DelegationOutcome.Error,
            Error = "Connection refused",
            DelegationDepth = 1,
            HopCount = 2
        };

        await sink.WriteAsync(record);

        loggerMock.Verify(
            x => x.Log(LogLevel.Error, It.IsAny<EventId>(),
                It.Is<It.IsAnyType>((v, t) => true), null,
                It.IsAny<Func<It.IsAnyType, Exception?, string>>()),
            Times.AtLeastOnce);
    }

    [Fact]
    public void SerilogMeshAuditSink_Name_IsCorrect()
    {
        var loggerMock = new Mock<ILogger<MeshAuditService>>();
        var sink = new SerilogMeshAuditSink(loggerMock.Object, DefaultConfig());

        Assert.Equal("SerilogMeshAuditSink", sink.Name);
        Assert.True(sink.IsEnabled);
    }

    // ── OpenTelemetryMeshAuditSink ─────────────────────────────────────────

    [Fact]
    public void OpenTelemetryMeshAuditSink_Name_IsCorrect()
    {
        var sink = new OpenTelemetryMeshAuditSink(DefaultConfig());

        Assert.Equal("OpenTelemetryMeshAuditSink", sink.Name);
    }

    // ── FileMeshAuditSink ──────────────────────────────────────────────────

    [Fact]
    public async Task FileMeshAuditSink_WriteAsync_CreatesJsonlFile()
    {
        var tempDir = Path.Combine(Path.GetTempPath(), $"mesh-audit-test-{Guid.NewGuid():N}");
        Directory.CreateDirectory(tempDir);
        var loggerMock = new Mock<ILogger<FileMeshAuditSink>>();
        var sink = new FileMeshAuditSink(tempDir, loggerMock.Object);
        var record = MakeRecord("outbound_delegation");

        try
        {
            await sink.WriteAsync(record);

            var files = Directory.GetFiles(tempDir, "mesh-audit-*.jsonl");
            Assert.Single(files);

            var lines = await File.ReadAllLinesAsync(files[0]);
            Assert.Single(lines);
            Assert.Contains("\"event_type\":\"outbound_delegation\"", lines[0]);
        }
        finally
        {
            sink.Dispose();
            try { if (Directory.Exists(tempDir)) Directory.Delete(tempDir, true); } catch { /* best effort */ }
        }
    }

    [Fact]
    public async Task FileMeshAuditSink_WriteAsync_AppendsMultipleLines()
    {
        var tempDir = Path.Combine(Path.GetTempPath(), $"mesh-audit-test-{Guid.NewGuid():N}");
        Directory.CreateDirectory(tempDir);
        var loggerMock = new Mock<ILogger<FileMeshAuditSink>>();
        var sink = new FileMeshAuditSink(tempDir, loggerMock.Object);

        try
        {
            await sink.WriteAsync(MakeRecord("outbound_delegation"));
            await sink.WriteAsync(MakeRecord("delegation_result"));
            await sink.WriteAsync(MakeRecord("task_state_change"));

            var files = Directory.GetFiles(tempDir, "mesh-audit-*.jsonl");
            var lines = await File.ReadAllLinesAsync(files[0]);
            Assert.Equal(3, lines.Length);
        }
        finally
        {
            sink.Dispose();
            try { if (Directory.Exists(tempDir)) Directory.Delete(tempDir, true); } catch { /* best effort */ }
        }
    }

    [Fact]
    public async Task FileMeshAuditSink_WriteAsync_IsIdempotentPerCall()
    {
        var tempDir = Path.Combine(Path.GetTempPath(), $"mesh-audit-test-{Guid.NewGuid():N}");
        Directory.CreateDirectory(tempDir);
        var loggerMock = new Mock<ILogger<FileMeshAuditSink>>();
        var sink = new FileMeshAuditSink(tempDir, loggerMock.Object);
        var record = MakeRecord();

        try
        {
            await sink.WriteAsync(record);
            await sink.WriteAsync(record);

            var files = Directory.GetFiles(tempDir, "mesh-audit-*.jsonl");
            var lines = await File.ReadAllLinesAsync(files[0]);
            Assert.Equal(2, lines.Length);
        }
        finally
        {
            sink.Dispose();
            try { if (Directory.Exists(tempDir)) Directory.Delete(tempDir, true); } catch { /* best effort */ }
        }
    }

    [Fact]
    public void FileMeshAuditSink_Name_IsCorrect()
    {
        var loggerMock = new Mock<ILogger<FileMeshAuditSink>>();
        using var sink = new FileMeshAuditSink(Path.GetTempPath(), loggerMock.Object);

        Assert.Equal("FileMeshAuditSink", sink.Name);
        Assert.True(sink.IsEnabled);
    }

    // ── MeshAuditService ────────────────────────────────────────────────────

    [Fact]
    public async Task MeshAuditService_LogOutboundDelegationAsync_InvokesAllEnabledSinks()
    {
        // Mock.Of returns default(bool)=false for IsEnabled, so set it explicitly via Mock.Get
        var sink1 = Mock.Of<IAuditSink>();
        var sink2 = Mock.Of<IAuditSink>();
        Mock.Get(sink1).SetupGet(s => s.IsEnabled).Returns(true);
        Mock.Get(sink2).SetupGet(s => s.IsEnabled).Returns(true);
        var loggerMock = new Mock<ILogger<MeshAuditService>>();
        var cfg = DefaultConfig();
        var svc = new MeshAuditService(new[] { sink1, sink2 }, cfg, loggerMock.Object);

        var envelope = IntentEnvelope.Create(
            "req-001", "agent-a", "csharp-refactor", """{"file":"foo.cs"}""",
            recipient: "agent-b");
        var transportResult = TransportResult.Ok(
            IntentResponse.Ok("req-001", "agent-b", "done"), 150, TransportKind.Http);

        await svc.LogOutboundDelegationAsync(
            envelope, "agent-a", "agent-b", transportResult,
            "Allowed", null, DataClassification.Internal);

        Mock.Get(sink1).Verify(s => s.WriteAsync(It.IsAny<InterAgentAuditRecord>(), It.IsAny<CancellationToken>()), Times.Once);
        Mock.Get(sink2).Verify(s => s.WriteAsync(It.IsAny<InterAgentAuditRecord>(), It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task MeshAuditService_LogDelegationResultAsync_WritesResultRecord()
    {
        var sink = Mock.Of<IAuditSink>();
        Mock.Get(sink).SetupGet(s => s.IsEnabled).Returns(true);
        var loggerMock = new Mock<ILogger<MeshAuditService>>();
        var cfg = DefaultConfig();
        var svc = new MeshAuditService(new[] { sink }, cfg, loggerMock.Object);

        var outboundRecord = MakeRecord("outbound_delegation");
        var response = IntentResponse.Ok("req-001", "agent-b", """{"status":"done"}""");

        await svc.LogDelegationResultAsync(outboundRecord, response, 150.0);

        Mock.Get(sink).Verify(s => s.WriteAsync(
            It.Is<InterAgentAuditRecord>(r =>
                r.EventType == "delegation_result" &&
                r.Outcome == DelegationOutcome.Ok),
            It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task MeshAuditService_LogDelegationResultAsync_ErrorOutcome_IncludesErrorMessage()
    {
        var sink = Mock.Of<IAuditSink>();
        Mock.Get(sink).SetupGet(s => s.IsEnabled).Returns(true);
        var loggerMock = new Mock<ILogger<MeshAuditService>>();
        var cfg = DefaultConfig();
        var svc = new MeshAuditService(new[] { sink }, cfg, loggerMock.Object);

        var outboundRecord = MakeRecord("outbound_delegation");
        var response = IntentResponse.Failed("req-001", "agent-b", "Connection refused");

        await svc.LogDelegationResultAsync(outboundRecord, response, 50.0);

        Mock.Get(sink).Verify(s => s.WriteAsync(
            It.Is<InterAgentAuditRecord>(r =>
                r.Outcome == DelegationOutcome.Error &&
                r.Error == "Connection refused"),
            It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task MeshAuditService_LogTaskStateChangeAsync_WritesTaskStateChangeRecord()
    {
        var sink = Mock.Of<IAuditSink>();
        Mock.Get(sink).SetupGet(s => s.IsEnabled).Returns(true);
        var loggerMock = new Mock<ILogger<MeshAuditService>>();
        var cfg = DefaultConfig();
        var svc = new MeshAuditService(new[] { sink }, cfg, loggerMock.Object);

        await svc.LogTaskStateChangeAsync(
            taskId: "task-001",
            requestId: "req-001",
            callerAgentId: "agent-caller",
            localAgentId: "agent-local",
            intent: "code-review",
            fromState: "Accepted",
            toState: "Completed",
            outcome: DelegationOutcome.Ok,
            error: null,
            latencyMs: 500.0);

        Mock.Get(sink).Verify(s => s.WriteAsync(
            It.Is<InterAgentAuditRecord>(r =>
                r.EventType == "task_state_change" &&
                r.SenderAgentId == "agent-caller" &&
                r.ReceiverAgentId == "agent-local" &&
                r.Intent == "code-review" &&
                r.Outcome == DelegationOutcome.Ok),
            It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task MeshAuditService_LogInboundDelegationAsync_WritesInboundRecord()
    {
        var sink = Mock.Of<IAuditSink>();
        Mock.Get(sink).SetupGet(s => s.IsEnabled).Returns(true);
        var loggerMock = new Mock<ILogger<MeshAuditService>>();
        var cfg = DefaultConfig();
        var svc = new MeshAuditService(new[] { sink }, cfg, loggerMock.Object);

        var envelope = IntentEnvelope.Create(
            "req-002", "agent-x", "security-scan", """{"repo":"my/repo"}""",
            recipient: "agent-local");

        await svc.LogInboundDelegationAsync(
            envelope, "agent-local", "Allowed", null, DataClassification.Confidential);

        Mock.Get(sink).Verify(s => s.WriteAsync(
            It.Is<InterAgentAuditRecord>(r =>
                r.EventType == "inbound_delegation" &&
                r.SenderAgentId == "agent-x" &&
                r.ReceiverAgentId == "agent-local" &&
                r.Intent == "security-scan" &&
                r.DataClassification == DataClassification.Confidential),
            It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public async Task MeshAuditService_DisabledConfig_SkipsAllSinks()
    {
        var sinkMock = new Mock<IAuditSink>();
        var loggerMock = new Mock<ILogger<MeshAuditService>>();
        var cfg = new MeshAuditConfig { Enabled = false };
        var svc = new MeshAuditService(new[] { sinkMock.Object }, cfg, loggerMock.Object);

        await svc.LogOutboundDelegationAsync(
            IntentEnvelope.Create("req", "a", "intent", "{}", recipient: "b"),
            "a", "b",
            TransportResult.Ok(IntentResponse.Ok("req", "b", "ok"), 10, TransportKind.Http),
            "Allowed", null, DataClassification.Public);

        sinkMock.Verify(s => s.WriteAsync(It.IsAny<InterAgentAuditRecord>(), It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task MeshAuditService_SampleRate_0_5_SamplesOutHalf()
    {
        var sinkMock = new Mock<IAuditSink>();
        var loggerMock = new Mock<ILogger<MeshAuditService>>();
        var cfg = new MeshAuditConfig { Enabled = true, SampleRate = 0.0 }; // sample out everything
        var svc = new MeshAuditService(new[] { sinkMock.Object }, cfg, loggerMock.Object);

        // Write many records — none should reach sinks due to 0% sampling
        for (int i = 0; i < 20; i++)
        {
            await svc.LogOutboundDelegationAsync(
                IntentEnvelope.Create($"req-{i}", "a", "intent", "{}", recipient: "b"),
                "a", "b",
                TransportResult.Ok(IntentResponse.Ok($"req-{i}", "b", "ok"), 10, TransportKind.Http),
                "Allowed", null, DataClassification.Public);
        }

        sinkMock.Verify(s => s.WriteAsync(It.IsAny<InterAgentAuditRecord>(), It.IsAny<CancellationToken>()), Times.Never);
    }

    [Fact]
    public async Task MeshAuditService_RedactPayloads_HidesPayloadHash()
    {
        var sink = Mock.Of<IAuditSink>();
        Mock.Get(sink).SetupGet(s => s.IsEnabled).Returns(true);
        var loggerMock = new Mock<ILogger<MeshAuditService>>();
        var cfg = new MeshAuditConfig { Enabled = true, RedactPayloads = true, PayloadHashEnabled = true };
        var svc = new MeshAuditService(new[] { sink }, cfg, loggerMock.Object);

        var envelope = IntentEnvelope.Create("req-001", "a", "intent", """{"secret":"value"}""", recipient: "b");

        await svc.LogInboundDelegationAsync(envelope, "b", "Allowed", null, DataClassification.Public);

        Mock.Get(sink).Verify(s => s.WriteAsync(
            It.Is<InterAgentAuditRecord>(r => r.PayloadHash == null),
            It.IsAny<CancellationToken>()), Times.Once);
    }

    [Fact]
    public void MeshAuditService_IsEnabled_TrueWhenNotDisposed()
    {
        var sinkMock = new Mock<IAuditSink>();
        var loggerMock = new Mock<ILogger<MeshAuditService>>();
        var cfg = DefaultConfig();
        var svc = new MeshAuditService(new[] { sinkMock.Object }, cfg, loggerMock.Object);

        Assert.True(svc.IsEnabled);
    }

    public void Dispose() { }
}
